# postgress creadentials

DB_NAME = "DB_NAME"
DB_ADDRESS = "HOST:PORT"
USER_NAME = "USER_NAME"
DB_PASSWORD = "PASSWORD"
SQLALCHEMY_DATABASE_URI = "postgresql+psycopg2://{}:{}@{}/{}".format(
    USER_NAME, DB_PASSWORD, DB_ADDRESS, DB_NAME
)

# twitter creadentials
# https://apps.twitter.com

CONSUMER_KEY = "YOUR_CONSUMER_KEY"
CONSUMER_SECRET = "YOUR_CONSUMER_SECRET"
ACCESS_TOKEN = "YOUR_ACCESS_TOKEN"
ACCESS_TOKEN_SECRET = "YOUR_ACCESS_TOKEN_SECRET"
